[build]
builder = "railpack"
buildCommand = "cd example && npm install && npm run build"

[deploy]
startCommand = "cd example && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
